const express = require("express");
const fetch = require("node-fetch");

const app = express();
app.use(express.json());

const ACCESS_TOKEN = process.env.ACCESS_TOKEN;

// ===== ゲーム状態 =====
const games = {};

// ===== Webhook =====
app.post("/webhook", async (req, res) => {
  const event = req.body.events?.[0];
    if (!event || event.type !== "message") {
        return res.send("OK");
          }

            const text = event.message.text.trim();
              const userId = event.source.userId;
                const groupId = event.source.groupId;

                  if (!groupId) {
                      await reply(event.replyToken, "グループで使ってね");
                          return res.send("OK");
                            }

                              const game = games[groupId] ??= {
                                  phase: "idle",
                                      players: {},
                                          liar: null,
                                              themes: {}
                                                };

                                                  let replyText = "";

                                                    // ===== コマンド =====

                                                      // ゲーム開始
                                                        if (text === "/liar") {
                                                            game.phase = "join";
                                                                game.players = {};
                                                                    game.liar = null;
                                                                        game.themes = {};

                                                                            replyText =
                                                                                  "🎭 嘘つきは誰だ 開始！\n" +
                                                                                        "参加する人は /join";
                                                                                          }

                                                                                            // 参加
                                                                                              else if (text === "/join") {
                                                                                                  if (game.phase !== "join") {
                                                                                                        replyText = "今は参加受付中じゃないよ";
                                                                                                            } else {
                                                                                                                  game.players[userId] = true;
                                                                                                                        replyText = "✅ 参加しました";
                                                                                                                            }
                                                                                                                              }

                                                                                                                                // 参加者一覧
                                                                                                                                  else if (text === "/players") {
                                                                                                                                      const count = Object.keys(game.players).length;
                                                                                                                                          replyText = `👥 現在の参加者：${count}人`;
                                                                                                                                            }

                                                                                                                                              // 開始（お題配布）
                                                                                                                                                else if (text === "/begin") {
                                                                                                                                                    const ids = Object.keys(game.players);
                                                                                                                                                        if (ids.length < 3) {
                                                                                                                                                              replyText = "人数が足りません（3人以上）";
                                                                                                                                                                  } else {
                                                                                                                                                                        game.phase = "play";

                                                                                                                                                                              // 嘘つき決定
                                                                                                                                                                                    game.liar = ids[Math.floor(Math.random() * ids.length)];

                                                                                                                                                                                          for (const id of ids) {
                                                                                                                                                                                                  if (id === game.liar) {
                                                                                                                                                                                                            game.themes[id] = "嫌いな食べ物";
                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                              game.themes[id] = "好きな食べ物";
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                              await push(
                                                                                                                                                                                                                                                        id,
                                                                                                                                                                                                                                                                  `🧠 お題：${game.themes[id]}\n1文で答えてください`
                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                      replyText =
                                                                                                                                                                                                                                                                                              "🗣️ お題を個別に送りました\n" +
                                                                                                                                                                                                                                                                                                      "全員1文で発言してください";
                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                              // 投票
                                                                                                                                                                                                                                                                                                                else if (text.startsWith("/vote")) {
                                                                                                                                                                                                                                                                                                                    if (game.phase !== "play") {
                                                                                                                                                                                                                                                                                                                          replyText = "今は投票フェーズじゃないよ";
                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                    replyText = "🗳️ 投票しました\n/result で結果発表";
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                            // 結果
                                                                                                                                                                                                                                                                                                                                              else if (text === "/result") {
                                                                                                                                                                                                                                                                                                                                                  if (!game.liar) {
                                                                                                                                                                                                                                                                                                                                                        replyText = "まだゲームが始まっていません";
                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                  replyText =
                                                                                                                                                                                                                                                                                                                                                                          "🎭 結果発表！\n" +
                                                                                                                                                                                                                                                                                                                                                                                  "嘘つきは……\n" +
                                                                                                                                                                                                                                                                                                                                                                                          "😈 この中にいます！\n\n" +
                                                                                                                                                                                                                                                                                                                                                                                                  "（正解は議論で決めてね）";

                                                                                                                                                                                                                                                                                                                                                                                                        game.phase = "idle";
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                // 強制終了
                                                                                                                                                                                                                                                                                                                                                                                                                  else if (text === "/cancel") {
                                                                                                                                                                                                                                                                                                                                                                                                                      delete games[groupId];
                                                                                                                                                                                                                                                                                                                                                                                                                          replyText = "❌ ゲームを終了しました";
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                              // ===== 返信 =====
                                                                                                                                                                                                                                                                                                                                                                                                                                if (replyText) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    await reply(event.replyToken, replyText);
                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                        res.send("OK");
                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                        // ===== LINE API =====
                                                                                                                                                                                                                                                                                                                                                                                                                                        async function reply(replyToken, text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          await fetch("https://api.line.me/v2/bot/message/reply", {
                                                                                                                                                                                                                                                                                                                                                                                                                                              method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Authorization": `Bearer ${ACCESS_TOKEN}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            replyToken,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  messages: [{ type: "text", text }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async function push(userId, text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await fetch("https://api.line.me/v2/bot/message/push", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Authorization": `Bearer ${ACCESS_TOKEN}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            to: userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  messages: [{ type: "text", text }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ===== サーバー起動 =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("Server running on port", PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });