const express = require("express");
const fetch = require("node-fetch");

const app = express();
app.use(express.json());

const ACCESS_TOKEN = process.env.ACCESS_TOKEN;

// ===== ゲーム状態（メモリ）=====
const games = {};

// ===== Webhook =====
app.post("/webhook", async (req, res) => {
  const event = req.body.events?.[0];
    if (!event || event.type !== "message") {
        return res.send("OK");
          }

            const text = event.message.text;
              const userId = event.source.userId;
                const groupId = event.source.groupId;

                  if (!groupId) {
                      await reply(event.replyToken, "グループで使ってね");
                          return res.send("OK");
                            }

                              const game = games[groupId] ??= {
                                  phase: "idle",
                                      players: {},
                                          roles: {},
                                              votes: {}
                                                };

                                                  let replyText = "";

                                                    // ===== コマンド =====
                                                      if (text === "/start") {
                                                          game.phase = "join";
                                                              game.players = {};
                                                                  replyText = "🐺 ワンナイト人狼開始！\n参加する人は /join";
                                                                    }

                                                                      else if (text === "/join") {
                                                                          if (game.phase !== "join") {
                                                                                replyText = "今は参加受付中じゃないよ";
                                                                                    } else {
                                                                                          game.players[userId] = true;
                                                                                                replyText = "✅ 参加しました";
                                                                                                    }
                                                                                                      }

                                                                                                        else if (text === "/begin") {
                                                                                                            const ids = Object.keys(game.players);
                                                                                                                if (ids.length < 2) {
                                                                                                                      replyText = "人数が足りません（2人以上）";
                                                                                                                          } else {
                                                                                                                                game.phase = "play";
                                                                                                                                      game.roles = {};
                                                                                                                                            game.votes = {};

                                                                                                                                                  const wolf = ids[Math.floor(Math.random() * ids.length)];
                                                                                                                                                        for (const id of ids) {
                                                                                                                                                                game.roles[id] = id === wolf ? "wolf" : "villager";
                                                                                                                                                                      }

                                                                                                                                                                            replyText = "🌙 夜が明けました。役職は個別に通知しました";

                                                                                                                                                                                  for (const id of ids) {
                                                                                                                                                                                          await push(
                                                                                                                                                                                                    id,
                                                                                                                                                                                                              game.roles[id] === "wolf"
                                                                                                                                                                                                                          ? "🐺 あなたは【人狼】です"
                                                                                                                                                                                                                                      : "🙂 あなたは【村人】です"
                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                            else if (text.startsWith("/vote")) {
                                                                                                                                                                                                                                                                if (game.phase !== "play") {
                                                                                                                                                                                                                                                                      replyText = "今は投票フェーズじゃないよ";
                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                const target = text.split(" ")[1];
                                                                                                                                                                                                                                                                                      game.votes[userId] = target;
                                                                                                                                                                                                                                                                                            replyText = "🗳️ 投票しました";
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                    else if (text === "/result") {
                                                                                                                                                                                                                                                                                                        const count = {};
                                                                                                                                                                                                                                                                                                            for (const v of Object.values(game.votes)) {
                                                                                                                                                                                                                                                                                                                  count[v] = (count[v] || 0) + 1;
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                          const result = Object.entries(count)
                                                                                                                                                                                                                                                                                                                                .sort((a, b) => b[1] - a[1])[0];

                                                                                                                                                                                                                                                                                                                                    const wolfId = Object.keys(game.roles)
                                                                                                                                                                                                                                                                                                                                          .find(id => game.roles[id] === "wolf");

                                                                                                                                                                                                                                                                                                                                              replyText =
                                                                                                                                                                                                                                                                                                                                                    result && result[0] === wolfId
                                                                                                                                                                                                                                                                                                                                                            ? "🎉 村人の勝利！人狼が処刑された！"
                                                                                                                                                                                                                                                                                                                                                                    : "💀 人狼の勝利！";

                                                                                                                                                                                                                                                                                                                                                                        game.phase = "idle";
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                            if (replyText) {
                                                                                                                                                                                                                                                                                                                                                                                await reply(event.replyToken, replyText);
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                    res.send("OK");
                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                    // ===== LINE API =====
                                                                                                                                                                                                                                                                                                                                                                                    async function reply(replyToken, text) {
                                                                                                                                                                                                                                                                                                                                                                                      await fetch("https://api.line.me/v2/bot/message/reply", {
                                                                                                                                                                                                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                                                                                                                                                                                                    "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                          "Authorization": `Bearer ${ACCESS_TOKEN}`
                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                        replyToken,
                                                                                                                                                                                                                                                                                                                                                                                                                              messages: [{ type: "text", text }]
                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    async function push(userId, text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                      await fetch("https://api.line.me/v2/bot/message/push", {
                                                                                                                                                                                                                                                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Authorization": `Bearer ${ACCESS_TOKEN}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to: userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              messages: [{ type: "text", text }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ===== サーバー起動 =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log("Server running on port", PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });