export default {
      async fetch(req, env) {
          if (req.method !== "POST") return new Response("OK");

              const body = await req.json();
                  const event = body.events?.[0];
                      if (!event || event.type !== "message") return new Response("OK");

                          const text = event.message.text;
                              const userId = event.source.userId;
                                  const groupId = event.source.groupId;

                                      // ===== ゲーム状態（メモリ）=====
                                          globalThis.games ??= {};
                                              const game = globalThis.games[groupId] ??= {
                                                    phase: "idle",
                                                          players: {},
                                                                roles: {},
                                                                      votes: {}
                                                                          };

                                                                              let reply = "";

                                                                                  // ===== コマンド =====
                                                                                      if (text === "/start") {
                                                                                            game.phase = "join";
                                                                                                  game.players = {};
                                                                                                        reply = "🐺 ワンナイト人狼開始！\n参加する人は /join";
                                                                                                            }

                                                                                                                else if (text === "/join") {
                                                                                                                      if (game.phase !== "join") {
                                                                                                                              reply = "今は参加受付中じゃないよ";
                                                                                                                                    } else {
                                                                                                                                            game.players[userId] = true;
                                                                                                                                                    reply = "✅ 参加しました";
                                                                                                                                                          }
                                                                                                                                                              }

                                                                                                                                                                  else if (text === "/begin") {
                                                                                                                                                                        const ids = Object.keys(game.players);
                                                                                                                                                                              if (ids.length < 2) {
                                                                                                                                                                                      reply = "人数が足りません（2人以上）";
                                                                                                                                                                                            } else {
                                                                                                                                                                                                    game.phase = "play";
                                                                                                                                                                                                            game.roles = {};
                                                                                                                                                                                                                    game.votes = {};

                                                                                                                                                                                                                            const wolf = ids[Math.floor(Math.random() * ids.length)];
                                                                                                                                                                                                                                    for (const id of ids) {
                                                                                                                                                                                                                                              game.roles[id] = id === wolf ? "wolf" : "villager";
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                              reply = "🌙 夜が明けました。役職は個別に通知しました";

                                                                                                                                                                                                                                                                      await Promise.all(
                                                                                                                                                                                                                                                                                ids.map(id =>
                                                                                                                                                                                                                                                                                            pushMessage(
                                                                                                                                                                                                                                                                                                          env,
                                                                                                                                                                                                                                                                                                                        id,
                                                                                                                                                                                                                                                                                                                                      game.roles[id] === "wolf"
                                                                                                                                                                                                                                                                                                                                                      ? "🐺 あなたは【人狼】です"
                                                                                                                                                                                                                                                                                                                                                                      : "🙂 あなたは【村人】です"
                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                  else if (text.startsWith("/vote")) {
                                                                                                                                                                                                                                                                                                                                                                                                                        if (game.phase !== "play") {
                                                                                                                                                                                                                                                                                                                                                                                                                                reply = "今は投票フェーズじゃないよ";
                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                              const target = text.split(" ")[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                      game.votes[userId] = target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              reply = "🗳️ 投票しました";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else if (text === "/result") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const count = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const v of Object.values(game.votes)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                count[v] = (count[v] || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const result = Object.entries(count)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .sort((a, b) => b[1] - a[1])[0];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const wolfId = Object.keys(game.roles)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .find(id => game.roles[id] === "wolf");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reply =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result && result[0] === wolfId
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "🎉 村人の勝利！人狼が処刑された！"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "💀 人狼の勝利！";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          game.phase = "idle";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (reply) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await replyMessage(env, event.replyToken, reply);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Response("OK");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ===== LINE API =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async function replyMessage(env, token, text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await fetch("https://api.line.me/v2/bot/message/reply", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Authorization": `Bearer ${env.ACCESS_TOKEN}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      replyToken: token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messages: [{ type: "text", text }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async function pushMessage(env, userId, text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await fetch("https://api.line.me/v2/bot/message/push", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Authorization": `Bearer ${env.ACCESS_TOKEN}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to: userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messages: [{ type: "text", text }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  