const http = require("http");
const ACCESS_TOKEN = process.env.ACCESS_TOKEN;

let game = {
  active: false,
    groupId: null,
      players: [],
        liar: null,
          votes: {}
          };

          // ===== LINE送信 =====
          function reply(replyToken, text) {
            return new Promise((resolve, reject) => {
                const data = JSON.stringify({
                      replyToken,
                            messages: [{ type: "text", text }]
                                });

                                    const options = {
                                          hostname: "api.line.me",
                                                path: "/v2/bot/message/reply",
                                                      method: "POST",
                                                            headers: {
                                                                    "Content-Type": "application/json",
                                                                            "Authorization": `Bearer ${ACCESS_TOKEN}`,
                                                                                    "Content-Length": Buffer.byteLength(data)
                                                                                          }
                                                                                              };

                                                                                                  const req = http.request(options, res => {
                                                                                                        res.on("data", () => {});
                                                                                                              res.on("end", resolve);
                                                                                                                  });

                                                                                                                      req.on("error", reject);
                                                                                                                          req.write(data);
                                                                                                                              req.end();
                                                                                                                                });
                                                                                                                                }

                                                                                                                                function push(userId, text) {
                                                                                                                                  return new Promise((resolve, reject) => {
                                                                                                                                      const data = JSON.stringify({
                                                                                                                                            to: userId,
                                                                                                                                                  messages: [{ type: "text", text }]
                                                                                                                                                      });

                                                                                                                                                          const options = {
                                                                                                                                                                hostname: "api.line.me",
                                                                                                                                                                      path: "/v2/bot/message/push",
                                                                                                                                                                            method: "POST",
                                                                                                                                                                                  headers: {
                                                                                                                                                                                          "Content-Type": "application/json",
                                                                                                                                                                                                  "Authorization": `Bearer ${ACCESS_TOKEN}`,
                                                                                                                                                                                                          "Content-Length": Buffer.byteLength(data)
                                                                                                                                                                                                                }
                                                                                                                                                                                                                    };

                                                                                                                                                                                                                        const req = http.request(options, res => {
                                                                                                                                                                                                                              res.on("data", () => {});
                                                                                                                                                                                                                                    res.on("end", resolve);
                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                            req.on("error", reject);
                                                                                                                                                                                                                                                req.write(data);
                                                                                                                                                                                                                                                    req.end();
                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                      // ===== Webhook =====
                                                                                                                                                                                                                                                      const server = http.createServer(async (req, res) => {
                                                                                                                                                                                                                                                        if (req.method !== "POST") {
                                                                                                                                                                                                                                                            res.writeHead(200);
                                                                                                                                                                                                                                                                res.end("OK");
                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                        let body = "";
                                                                                                                                                                                                                                                                          req.on("data", chunk => (body += chunk.toString()));
                                                                                                                                                                                                                                                                            req.on("end", async () => {
                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                      const events = JSON.parse(body).events || [];

                                                                                                                                                                                                                                                                                            for (const e of events) {
                                                                                                                                                                                                                                                                                                    if (e.type !== "message" || e.message.type !== "text") continue;

                                                                                                                                                                                                                                                                                                            const text = e.message.text.trim();
                                                                                                                                                                                                                                                                                                                    const replyToken = e.replyToken;
                                                                                                                                                                                                                                                                                                                            const userId = e.source.userId;
                                                                                                                                                                                                                                                                                                                                    const groupId = e.source.groupId;

                                                                                                                                                                                                                                                                                                                                            // ===== コマンド =====
                                                                                                                                                                                                                                                                                                                                                    if (text === "/liar start") {
                                                                                                                                                                                                                                                                                                                                                              game = { active: true, groupId, players: [], liar: null, votes: {} };
                                                                                                                                                                                                                                                                                                                                                                        await reply(replyToken, "🎭 嘘つきは誰だ 募集開始！ /join で参加");
                                                                                                                                                                                                                                                                                                                                                                                } else if (text === "/join" && game.active && game.groupId === groupId) {
                                                                                                                                                                                                                                                                                                                                                                                          if (!game.players.includes(userId)) game.players.push(userId);
                                                                                                                                                                                                                                                                                                                                                                                                    await reply(replyToken, "✅ 参加しました");
                                                                                                                                                                                                                                                                                                                                                                                                            } else if (text === "/liar begin" && game.active) {
                                                                                                                                                                                                                                                                                                                                                                                                                      if (game.players.length < 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                  await reply(replyToken, "⚠️ 3人以上必要です");
                                                                                                                                                                                                                                                                                                                                                                                                                                              continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  game.liar = game.players[Math.floor(Math.random() * game.players.length)];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const id of game.players) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (id === game.liar) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await push(id, "🤥 あなたは【嘘つき】です。バレないように！");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await push(id, "🗣 お題：【好きな食べ物】 正直に答えてください");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await reply(replyToken, "💬 会話スタート！投票は /vote userId");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (text.startsWith("/vote ") && game.active) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const target = text.split(" ")[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            game.votes[userId] = target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await reply(replyToken, "🗳 投票しました");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else if (text === "/liar end" && game.active) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const result = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (const v of Object.values(game.votes)) result[v] = (result[v] || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let max = 0, selected = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (const id in result) if (result[id] > max) { max = result[id]; selected = id; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const win = selected === game.liar ? "🎉 正解！嘘つきを当てました！" : "💀 ハズレ！嘘つきの勝ち！";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await reply(replyToken, win);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    game.active = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.writeHead(200);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.end("OK");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ===== 起動 =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          server.listen(PORT, () => console.log("超軽量 嘘つきBOT 起動"));